// <auto-generated />
using System;
using G23NHNT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G23NHNT.Migrations
{
    [DbContext(typeof(G23_NHNTContext))]
    [Migration("20241115100610_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("G23NHNT.Models.Account", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.HasKey("IdUser")
                        .HasName("PK__Account__3717C98210B6EA83");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("G23NHNT.Models.Amenity", b =>
                {
                    b.Property<int>("IdAmenity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAmenity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAmenity"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdAmenity")
                        .HasName("PK__Amenitie__C1B0D589CDE1290A");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("G23NHNT.Models.House", b =>
                {
                    b.Property<int>("IdHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHouse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHouse"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("NameHouse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameHouse");

                    b.HasKey("IdHouse")
                        .HasName("PK__House__AF515CBF563343EC");

                    b.HasIndex("IdUser");

                    b.ToTable("House", (string)null);
                });

            modelBuilder.Entity("G23NHNT.Models.HouseDetail", b =>
                {
                    b.Property<int>("IdHouseDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHouseDetail");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHouseDetail"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Describe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("describe");

                    b.Property<double>("DienTich")
                        .HasColumnType("float")
                        .HasColumnName("dienTich");

                    b.Property<int>("IdHouse")
                        .HasColumnType("int")
                        .HasColumnName("idHouse");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TienDien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tienDien");

                    b.Property<string>("TienDv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tienDV");

                    b.Property<string>("TienNuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tienNuoc");

                    b.Property<DateTime>("TimePost")
                        .HasColumnType("datetime")
                        .HasColumnName("timePost");

                    b.HasKey("IdHouseDetail")
                        .HasName("PK__HouseDet__946F757FD8C7B0A6");

                    b.HasIndex("IdHouse");

                    b.ToTable("HouseDetail", (string)null);
                });

            modelBuilder.Entity("G23NHNT.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReview");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("IdHouse")
                        .HasColumnType("int")
                        .HasColumnName("idHouse");

                    b.Property<int?>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("reviewDate")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdReview")
                        .HasName("PK__Review__04F7FE108ECD5FA1");

                    b.HasIndex("IdHouse");

                    b.HasIndex("IdUser");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("HouseAmenity", b =>
                {
                    b.Property<int>("IdHouse")
                        .HasColumnType("int")
                        .HasColumnName("idHouse");

                    b.Property<int>("IdAmenity")
                        .HasColumnType("int")
                        .HasColumnName("idAmenity");

                    b.HasKey("IdHouse", "IdAmenity")
                        .HasName("PK__HouseAme__234A51E7ED05E3B2");

                    b.HasIndex("IdAmenity");

                    b.ToTable("HouseAmenities", (string)null);
                });

            modelBuilder.Entity("G23NHNT.Models.House", b =>
                {
                    b.HasOne("G23NHNT.Models.Account", "IdUserNavigation")
                        .WithMany("Houses")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_House_Account");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("G23NHNT.Models.HouseDetail", b =>
                {
                    b.HasOne("G23NHNT.Models.House", "IdHouseNavigation")
                        .WithMany("HouseDetails")
                        .HasForeignKey("IdHouse")
                        .IsRequired()
                        .HasConstraintName("FK_HouseDetail_House");

                    b.Navigation("IdHouseNavigation");
                });

            modelBuilder.Entity("G23NHNT.Models.Review", b =>
                {
                    b.HasOne("G23NHNT.Models.House", "IdHouseNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdHouse")
                        .HasConstraintName("FK__Review__idHouse__66603565");

                    b.HasOne("G23NHNT.Models.Account", "IdUserNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK__Review__idUser__6477ECF3");

                    b.Navigation("IdHouseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("HouseAmenity", b =>
                {
                    b.HasOne("G23NHNT.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("IdAmenity")
                        .IsRequired()
                        .HasConstraintName("FK__HouseAmen__idAme__5FB337D6");

                    b.HasOne("G23NHNT.Models.House", null)
                        .WithMany()
                        .HasForeignKey("IdHouse")
                        .IsRequired()
                        .HasConstraintName("FK__HouseAmen__idHou__5EBF139D");
                });

            modelBuilder.Entity("G23NHNT.Models.Account", b =>
                {
                    b.Navigation("Houses");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("G23NHNT.Models.House", b =>
                {
                    b.Navigation("HouseDetails");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
